<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProgramsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('programs')->insert(
            [
                [
                    'name' => 'Doctor of Philosophy in Engineering',
                    'image_url' => 'https://example.com/images/phd_engineering.png',
                    'description' => 'Advanced research in engineering.',
                    'duration' => '3 years',
                    'study_mode' => 'On Campus',
                    'intake' => 'Ongoing',
                    'fee_per_year' => '25000',
                    'scholarship_percentage' => '30',
                    'scholarship_fee_per_year' => '17500',
                    'university_id' => 1,
                    'degree_id' => 1,
                    'department_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Doctor of Business Administration (DBA)',
                    'image_url' => 'https://example.com/images/dba.png',
                    'description' => 'Professional doctorate in business administration.',
                    'duration' => '3 years',
                    'study_mode' => 'On Campus',
                    'intake' => 'Ongoing',
                    'fee_per_year' => '30000',
                    'scholarship_percentage' => '25',
                    'scholarship_fee_per_year' => '22500',
                    'university_id' => 1,
                    'degree_id' => 2,
                    'department_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Bachelor (Hons) in International Business Management',
                    'image_url' => 'https://example.com/images/international_business.png',
                    'description' => 'Undergraduate program in international business.',
                    'duration' => '3 years',
                    'study_mode' => 'On Campus',
                    'intake' => 'Ongoing',
                    'fee_per_year' => '20000',
                    'scholarship_percentage' => '20',
                    'scholarship_fee_per_year' => '16000',
                    'university_id' => 1,
                    'degree_id' => 3,
                    'department_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PhD in Finance',
                    'image_url' => 'https://example.com/images/phd_finance.png',
                    'description' => 'Advanced research in finance.',
                    'duration' => '3 years',
                    'study_mode' => 'On Campus',
                    'intake' => 'Ongoing',
                    'fee_per_year' => '27000',
                    'scholarship_percentage' => '30',
                    'scholarship_fee_per_year' => '18900',
                    'university_id' => 1,
                    'degree_id' => 1,
                    'department_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Master of Science in Computing',
                    'image_url' => 'https://example.com/images/msc_computing.png',
                    'description' => 'Graduate program in computing.',
                    'duration' => '2 years',
                    'study_mode' => 'On Campus',
                    'intake' => 'Ongoing',
                    'fee_per_year' => '22000',
                    'scholarship_percentage' => '25',
                    'scholarship_fee_per_year' => '16500',
                    'university_id' => 1,
                    'degree_id' => 1,
                    'department_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Doctor of Philosophy in Engineering',
                    'image_url' => 'https://example.com/images/phd_engineering.png',
                    'description' => 'Advanced research in engineering.',
                    'duration' => '3 years',
                    'study_mode' => 'On Campus',
                    'intake' => 'Ongoing',
                    'fee_per_year' => '25000',
                    'scholarship_percentage' => '30',
                    'scholarship_fee_per_year' => '17500',
                    'university_id' => 1,
                    'degree_id' => 1,
                    'department_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Doctor of Business Administration (DBA)',
                    'image_url' => 'https://example.com/images/dba.png',
                    'description' => 'Professional doctorate in business administration.',
                    'duration' => '3 years',
                    'study_mode' => 'On Campus',
                    'intake' => 'Ongoing',
                    'fee_per_year' => '30000',
                    'scholarship_percentage' => '25',
                    'scholarship_fee_per_year' => '22500',
                    'university_id' => 1,
                    'degree_id' => 2,
                    'department_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Bachelor (Hons) in International Business Management',
                    'image_url' => 'https://example.com/images/international_business.png',
                    'description' => 'Undergraduate program in international business.',
                    'duration' => '3 years',
                    'study_mode' => 'On Campus',
                    'intake' => 'Ongoing',
                    'fee_per_year' => '20000',
                    'scholarship_percentage' => '20',
                    'scholarship_fee_per_year' => '16000',
                    'university_id' => 1,
                    'degree_id' => 2,
                    'department_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PhD in Finance',
                    'image_url' => 'https://example.com/images/phd_finance.png',
                    'description' => 'Advanced research in finance.',
                    'duration' => '3 years',
                    'study_mode' => 'On Campus',
                    'intake' => 'Ongoing',
                    'fee_per_year' => '27000',
                    'scholarship_percentage' => '30',
                    'scholarship_fee_per_year' => '18900',
                    'university_id' => 1,
                    'degree_id' => 2,
                    'department_id' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Master of Science in Computing',
                    'image_url' => 'https://example.com/images/msc_computing.png',
                    'description' => 'Graduate program in computing.',
                    'duration' => '2 years',
                    'study_mode' => 'On Campus',
                    'intake' => 'Ongoing',
                    'fee_per_year' => '22000',
                    'scholarship_percentage' => '25',
                    'scholarship_fee_per_year' => '16500',
                    'university_id' => 1,
                    'degree_id' => 2,
                    'department_id' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
        );
    }
}
